name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Deploy
        uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: Tony Wang
          email: plantpark.net@gmail.com