name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Setup Hexo
        uses: heowc/action-hexo@master
        with:
          args: generate

      - name: Build
        run: npm install && hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public