name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "10.x"
  
      - name: Setup Hexo env
        run: |
          # install dependencies
          npm i -g hexo-cli # 安装hexo
          npm i

      - name: Build
        run: hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public