name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Deploy
        uses: heowc/action-hexo@master
        env:
          EMAIL: plantpark.net@gmail.com
          NAME: Tony Wang
        with:
          args: deploy