name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean

      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Deploy
        uses: heowc/action-hexo@master
        env:
          EMAIL: input emial ...
          NAME: input name ...
        with:
          args: deploy
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v2.5.0
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: ./public