name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 8.x
          
      - name: Installation
        run: |
          npm install
          npm install -g hexo-cli

      - name: Deploy
        uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: Tony Wang
          email: plantpark.net@gmail.com